#!/bin/bash

# Find the IP of the Fire TV:
# Settings > Device > About > Network - shows the IP address
# More info: https://developer.amazon.com/docs/fire-tv/connecting-adb-to-device.html#networkconnect

adb kill-server
adb start-server
adb connect $1:5555
adb devices