//------------- ERROR MESSAGE CODES --------------
// For use in createWith(ErrorCode)
#define ERROR_CODE_SOMETHING_WENT_WRONG -2
#define ERROR_CODE_INVALID_CREDENTIALS 1001
#define ERROR_CODE_ANY_OTHER_LOGIN_ERROR 1002
#define ERROR_CODE_EMAIL_VARIFICATION_REQUIRED 1003
#define ERROR_CODE_INCORRECT_PIN 1004
#define ERROR_CODE_NAME_EXISTS 1005
#define ERROR_CODE_LOGGED_YOU_BACK_IN 1006
#define ERROR_CODE_BAD_TIME_SETTING 2001

#define ERROR_CODE_PURCHASE_FAILURE 3002
#define ERROR_CODE_PURCHASE_DOUBLE 3003
#define ERROR_CODE_PURCHASE_FAILURE_CONTACT_US 3004
