#ifndef AzoomeeCommon_ErrorCodes_h
#define AzoomeeCommon_ErrorCodes_h

//------------- ERROR MESSAGE CODES --------------
// For use in createWith(ErrorCode)
#define ERROR_CODE_SOMETHING_WENT_WRONG -2

#define ERROR_CODE_INVALID_CREDENTIALS 1001
#define ERROR_CODE_ANY_OTHER_LOGIN_ERROR 1002
#define ERROR_CODE_EMAIL_VARIFICATION_REQUIRED 1003
#define ERROR_CODE_INCORRECT_PIN 1004
#define ERROR_CODE_NAME_EXISTS 1005
#define ERROR_CODE_DEEPLINK_NOT_ENTITLED 1007
#define ERROR_CODE_BAD_TIME_SETTING 2001

#define ERROR_CODE_PURCHASE_FAILURE 3002
#define ERROR_CODE_PURCHASE_DOUBLE 3003
#define ERROR_CODE_APPLE_SUB_REFRESH_FAIL 3004
#define ERROR_CODE_APPLE_NO_PREVIOUS_PURCHASE 3005
#define ERROR_CODE_APPLE_ACCOUNT_DOWNGRADED 3006
#define ERROR_CODE_APPLE_SUBSCRIPTION_ON_NON_APPLE 3007

#define ERROR_CODE_GAME_INCOMPATIBLE 4001

//---------CHAT ERROR CODES---------------
#define ERROR_CODE_REPORT_MESSAGES 5001
#define ERROR_CODE_RESET_REPORTED_CHAT 5002

//---------PREVIEW SIGNIN / LOGIN MESSAGE ----------
#define PREVIEW_SIGNIN_LOGIN 6001

#endif
